# Generated by Django 3.2.4 on 2021-06-12 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fsite', '0003_auto_20210610_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AlterField(
            model_name='post',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='post',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='fsite.brands', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='articles/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='post',
            name='mileage',
            field=models.IntegerField(default=0, verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='post',
            name='number',
            field=models.CharField(max_length=13, verbose_name='Ваш номер'),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='Причина продажи'),
        ),
    ]
